# CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  # Install dependencies & run tests.
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: circleci/mariadb:10.3
        environment:
          MYSQL_DATABASE: rogue_test
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
      - image: circleci/mongo:4.0.13
      - image: circleci/redis:4.0.14
    steps:
      # Check out source code for this branch & install dependencies.
      # If we can, we'll load these from cache (based on the lockfile).
      - checkout
      - run: sudo composer self-update
      # Install PHP extensions required by Laravel & MongoDB.
      - run:
          name: install php extensions
          command: |
            sudo pecl install mongodb redis
            sudo apt-get install libpng-dev libjpeg-dev
            sudo docker-php-ext-configure gd --with-jpeg
            sudo docker-php-ext-enable mongodb redis
            sudo docker-php-ext-install bcmath pdo_mysql gettext gd exif
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package-lock.json" }}
            - node-v2-
      - run: npm install
      - save_cache:
          key: node-v2-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: check php code style
          command: vendor/bin/php-cs-fixer fix --dry-run --no-interaction --verbose
      - run: npm run build
      - run: php artisan northstar:setup
      - run:
          name: run phpunit tests
          command: |
            mkdir -p ~/phpunit
            vendor/bin/phpunit -d memory_limit=512M --log-junit ~/phpunit/junit.xml
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/phpunit
